#!/usr/bin/env python3

from pathlib import Path
import runpy

runpy.run_path(str(Path(__file__).parent / "bootstrap_venvstarter.py"))

manager = __import__("venvstarter").manager("noy_pylama")
manager.add_pypi_deps("pylama==8.3.7", "mypy==0.931", "pylama-dmypy==0.2", "noseOfYeti==2.3.1")
manager.add_local_dep(
    "{here}",
    "..",
    version_file=(
        "noy_black",
        "__init__.py",
    ),
    name="noy_black=={version}",
    with_tests=True,
)
manager.run()
